### ISSUE TITLE
Authentication failed.

### ISSUE THREAD

**Issue by Bearsaerker** [theonlyway/openlifter#5]
I love the idea so far, but I don't know if this is a bug or if I'm doing something wrong. I set it up exactly as you've written in your documentation. I build the docker containers for both the database and the openlifter_api. But I get following error message when clicking on "Test Connection" on the streaming tab 

Connection to API was successful
API connection to database failed
API failure message: "Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed'}"

I somehow don't get it solved by myself.

**Comment by theonlyway** [comment]
I haven't seen that before but it reads like the API might be failing to authenticate to MongoDB. 

Did you build the containers manually by building the dockerfiles or did you just use the docker-compose config? If you manually built the containers and then are running them manually without docker-compose I would probably make sure you are atleast passing in equivilant configuration for both mongodb and the api as defined in: https://github.com/theonlyway/openlifter/blob/main/docker/docker-compose.yml (https://github.com/theonlyway/openlifter/blob/main/docker/docker-compose.yml#L16 is pretty important since it does create the user the API uses to connect to the DB)

If you've done that before you click test connection ensure you've opened the Development Tools in your browser, go to the network tab then hit test connection then return the request headers from the `GET` request to the `/health` endpoint

Additionally from the command line try running: `docker logs openlifter_api` and return the logs from the API
